create table lanternfish (timer int);

insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (2);
insert into lanternfish values (1);
insert into lanternfish values (5);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (2);
insert into lanternfish values (1);
insert into lanternfish values (4);
insert into lanternfish values (1);
insert into lanternfish values (4);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (4);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (4);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (5);
insert into lanternfish values (1);
insert into lanternfish values (3);
insert into lanternfish values (1);
insert into lanternfish values (2);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (2);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (4);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (3);
insert into lanternfish values (1);
insert into lanternfish values (5);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (3);
insert into lanternfish values (5);
insert into lanternfish values (5);
insert into lanternfish values (2);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (2);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (5);
insert into lanternfish values (4);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (3);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (2);
insert into lanternfish values (4);
insert into lanternfish values (4);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (3);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (5);
insert into lanternfish values (1);
insert into lanternfish values (3);
insert into lanternfish values (1);
insert into lanternfish values (5);
insert into lanternfish values (1);
insert into lanternfish values (2);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (5);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (5);
insert into lanternfish values (3);
insert into lanternfish values (3);
insert into lanternfish values (1);
insert into lanternfish values (4);
insert into lanternfish values (1);
insert into lanternfish values (3);
insert into lanternfish values (1);
insert into lanternfish values (3);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (3);
insert into lanternfish values (1);
insert into lanternfish values (4);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (2);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (4);
insert into lanternfish values (2);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (5);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (2);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (2);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (5);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (3);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (3);
insert into lanternfish values (4);
insert into lanternfish values (1);
insert into lanternfish values (2);
insert into lanternfish values (1);
insert into lanternfish values (3);
insert into lanternfish values (2);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (2);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (4);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (4);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (2);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (4);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (5);
insert into lanternfish values (3);
insert into lanternfish values (2);
insert into lanternfish values (2);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (3);
insert into lanternfish values (1);
insert into lanternfish values (5);
insert into lanternfish values (1);
insert into lanternfish values (5);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (5);
insert into lanternfish values (1);
insert into lanternfish values (4);
insert into lanternfish values (1);
insert into lanternfish values (2);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (2);
insert into lanternfish values (1);
insert into lanternfish values (3);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (2);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (3);
insert into lanternfish values (1);
insert into lanternfish values (4);
insert into lanternfish values (3);
insert into lanternfish values (1);
insert into lanternfish values (4);
insert into lanternfish values (1);
insert into lanternfish values (3);
insert into lanternfish values (2);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (3);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (2);
insert into lanternfish values (1);
insert into lanternfish values (5);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (2);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (3);
insert into lanternfish values (5);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (5);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (2);
insert into lanternfish values (1);
insert into lanternfish values (2);
insert into lanternfish values (4);
insert into lanternfish values (2);
insert into lanternfish values (2);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (5);
insert into lanternfish values (2);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (5);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (5);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (1);
insert into lanternfish values (2);
insert into lanternfish values (1);
commit;

create table fish as 
select timer, count(*) cnt from lanternfish group by timer;
insert into fish values (0, 0);
insert into fish values (6, 0);
insert into fish values (7, 0);
insert into fish values (8, 0);
commit;

create table fish_orig as select * from fish;

create or replace procedure fish_day is
    l_spawn number;
begin
    select cnt into l_spawn from fish where timer=0;
    delete from fish where timer=0;
    update fish set timer = timer-1;
    insert into fish (timer, cnt) values (8, l_spawn);
    update fish set cnt = cnt + l_spawn where timer=6;
end fish_day;
/

-- part 1
begin
    for i in 1..80 loop
        fish_day;
    end loop;
    commit;
end;
/
select sum(cnt) part1_answer from fish;

-- part 2
drop table fish purge;
create table fish as select * from fish_orig;

begin
    for i in 1..256 loop
        fish_day;
    end loop;
    commit;
end;
/

select sum(cnt) part2_answer from fish;
